export const DATA_DOWNLOADED_SUCCESSFULLY = 'dataSuccessfullyDownloadedFromApi';
export const NO_OF_WORD_LIST = 'totalNo';
export const DATADOWNLOADED = 'wordsAlreadyDownloaded';
export const ALL_WORD_INFO_URL = 'http://18.221.100.118:8080/get-all-words';
export const ALL_WORD_COUNT_URL = 'http://18.221.100.118:8080/get-all-word-count';
export const WORD_LIST_SELECTED = 'word list is selected for learning';
export const WORD_GROUP_SELECTED = 'word group selected';
export const WORD_GROUP_REFRESH = 'refresh word group evertime focus is made';
export const SEARCH_WORD = 'search word or wordGroup';
export const LEVEL_EASY = 'easy';
export const LEVEL_MEDIUM = 'medium';
export const LEVEL_HARD = 'hard';
export const LEVEL_UPDATE_SUCCESSFULL = 'word difficulty level updated successfully'
export const SHOW_WORD_LIST = 'get word list detail';
export const REVISE_MENU = 'it contain revise menu detail';
export const REVISE_LEVEL_SELECTED = 'details of selected word list and it difficulty level';
export const NOTE_TEXT_CHANGE = 'change in note text';
export const NOTE_UPDATED = 'note updated in database';
export const APP_THEME = '#673ab7';
